name: CI 

on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.0
        
      - name: Install python dependencies
        run : pip install flake8 
        
      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          flake8: true
        
      - name: Versioning 
        uses: github.com/pradeept/gitops/.github/workflows/versioning.yaml@workflow
